/* eslint-disable @next/next/inline-script-id */
/* eslint-disable react-hooks/exhaustive-deps */
import React, { useEffect, useState } from 'react';
import Layout from '../components/Layout';
import Script from 'next/script';
import type { GetStaticProps, NextPage } from 'next';
import { FieldSet } from 'airtable';
import Head from 'next/head';
import { StationListBox } from '../components/StationListBox';
import { SwitchHorizontalIcon } from '@heroicons/react/solid';
import { useLocalStorage } from '../lib/hooks/useLocalStorage';

const Home: NextPage<{
  stationData: FieldSet[] | undefined;
  busData: FieldSet[] | undefined;
}> = ({ stationData, busData }) => {
  const [stationNameFrom, setStationNameFrom] =
    useLocalStorage('stationNameFrom');
  const [stationNameTo, setStationNameTo] = useLocalStorage('stationNameTo');
  const [stationDataFrom, setStationDataFrom] = useState<
    FieldSet | undefined
  >();
  const [stationDataTo, setStationDataTo] = useState<FieldSet | undefined>();

  // localStorageからデータを呼んでメニューとライスを設定
  useEffect(() => {
    if (stationNameFrom === '') {
      setStationDataFrom(stationData && stationData[0]);
    } else {
      setStationDataFrom(
        stationData &&
          stationData.find(function (record) {
            return (record.fields as any).Name === stationNameFrom;
          })
      );
    }

    if (stationNameTo === '') {
      setStationDataTo(stationData && stationData[1]);
    } else {
      setStationDataTo(
        stationData &&
          stationData.find(function (record) {
            return (record.fields as any).Name === stationNameTo;
          })
      );
    }
  }, []);

  useEffect(() => {
    // メニューとライスをローカルストレージに保存
    if (stationDataFrom) {
      setStationNameFrom((stationDataFrom?.fields as any).Name);
    }
    if (stationDataTo) {
      setStationNameTo((stationDataTo?.fields as any).Name);
    }
  }, [stationDataFrom, stationDataTo]);

  return (
    <>
      <Layout>
        <Head>
          <title>今日のお弁当</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/obento.min.svg' />
        </Head>
        <main className='flex-col p-2 min-h-screen'>
          <h1 className='flex justify-center mb-4 text-4xl font-bold text-gray-600/80'>
            メニュー
          </h1>
          <StationListBox
            label='メニュー：'
            stations={stationData}
            selected={stationDataFrom}
            setSelected={setStationDataFrom}
          />
          <StationListBox
            label='ライス：'
            stations={stationData}
            selected={stationDataTo}
            setSelected={setStationDataTo}
          />
        </main>
      </Layout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  try {
    const origin = process.env.AUTH0_BASE_URL ?? 'http://localhost:3000';
    const res_station = await fetch(`${origin}/api/getStation`);
    return {
      props: {
        stationData: await res_station.json(),
      },
    };
  } catch (err) {
    console.error(err);
    return {
      props: {
        err: 'データ取得で問題が発生しました。',
      },
    };
  }
};

export default Home;
